version: 2
jobs:
  bucklescript-build-and-test:
    docker:
      - image: circleci/node:12

    environment:
      CI: true
      NODE_ENV: test

    working_directory: ~/repo/bucklescript
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-bucklescript-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-bucklescript-dependencies-{{ .Branch }}-
            - v1-bucklescript-dependencies-

      - run: npm install
      - run: npm run build
      - run: npm test

      - save_cache:
          key: v1-bucklescript-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/repo/bucklescript/node_modules

  native-build-and-test:
    docker:
      - image: circleci/node:12
    environment:
      CI: true
    working_directory: ~/repo/native
    steps:
      - checkout:
          path: ~/repo
      # m4 is a system dependency required by conf-m4 -> ocamlfind -> fmt -> alcotest
      - run: sudo apt-get install -y m4
      
      # Installing without setting a prefix leads to permission errors
      - run: 
          name: "Install esy"
          command: |
            mkdir -p ~/.npm-global
            npm config set prefix ~/.npm-global
            npm install -g esy

      - run: ~/.npm-global/bin/esy install
      - run: ~/.npm-global/bin/esy build
      - run: ~/.npm-global/bin/esy test
      - run: ~/.npm-global/bin/esy doc

workflows:
  version: 2
  build:
    jobs:
      - bucklescript-build-and-test
      - native-build-and-test
